-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES (Users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  name text,
  role text check (role in ('ADMIN', 'VENDOR', 'USER')) default 'USER',
  status text check (status in ('ACTIVE', 'SUSPENDED')) default 'ACTIVE',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- RLS for Profiles
alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- CATEGORIES
create table public.categories (
  id bigint generated by default as identity primary key,
  label text not null,
  icon text,
  color text
);

-- PRODUCTS
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text,
  price numeric not null,
  stock integer default 0,
  category text,
  image text,
  status text default 'ACTIVE',
  vendor_id uuid references public.profiles(id),
  vendor_name text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- KITS
create table public.kits (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  original_price numeric,
  image text,
  status text default 'ACTIVE',
  vendor_id uuid references public.profiles(id),
  items jsonb
);

-- ORDERS
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  total numeric not null,
  status text default 'PROCESSING',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  items jsonb
);
